<?php

namespace App\Jobs;

use App\Models\User;
use App\Models\UserChannel;
use Osiset\ShopifyApp\Actions\CancelCurrentPlan;
use Osiset\ShopifyApp\Contracts\Commands\Shop as IShopCommand;
use Osiset\ShopifyApp\Contracts\Queries\Shop as IShopQuery;
use Osiset\ShopifyApp\Objects\Values\ShopDomain;

class AppUninstalledJob extends \Osiset\ShopifyApp\Messaging\Jobs\AppUninstalledJob
{
    public function handle(IShopCommand $shopCommand, IShopQuery $shopQuery, CancelCurrentPlan $cancelCurrentPlanAction): bool
    {
        try {
            $user = User::where('name', $this->domain)->first();
            if ($user)
            UserChannel::where('user_id', $user->id)->delete();
        } catch (\Exception $exception) {

        }
        return parent::handle($shopCommand, $shopQuery, $cancelCurrentPlanAction); // TODO: Change the autogenerated stub
    }
}
